### ISSUE TITLE
Rings across branches.

### ISSUE THREAD

**Issue by TravelLeraLone** [baoilleach/deepsmiles#21]
If I'm not mistaken, the current version of Deepsmiles cannot handle the ring in smiles such as `CCCC(CC1)C(CC1)CCCC` directly. (The example smiles is valid although not canonical.)
If I input the example smile into the current code, the output will be `CCCCCC))CCC2))CCCC` which makes no sense at all.

The reason for this may lie in the DFS constraint you mentioned in  #6.

I am wondering whether this issue is worth fixing and whether this pattern will appear in canonical smiles.

**Comment by baoilleach** [comment]
As you've found, it's possible to construct a string that looks like DeepSMILES which the code doesn't handle. I don't regard this as a bug. It only supports conversion of SMILES that are written by a toolkit. It not a question of canonical SMILES; no SMILES writer will ever write that string - why would it stop to make a ring closure at the first "1"? From the preprint: "Since the successive atoms in a SMILES string occur in depth-first traversal order and thus form a tree, for any atom there is a single path back to the first atom; thus the ring size can be used as a distance along that path to unambiguously identify the location of the ring opening." If the string violates this assumption/requirement then the behaviour is undefined. The fix is simple though; just run it through a SMILES reader/writer.

**Comment by baoilleach** [comment]
Actually the paper describes this exact case: "To generate a DeepSMILES string we transform a SMILES string into an alternative syntax that
preserves atom order but modifies ring closure symbols and parentheses (see Table 1). The
transformation process does not require chemical interpretation of SMILES but only involves string
processing of the syntax. As such, it makes certain assumptions about the form of the SMILES string
that will be met if the SMILES string was generated by a standard cheminformatics toolkit, but may
not be met otherwise. For example, the code assumes that the SMILES was generated as a depth-
first traversal of the molecular graph. For example, this assumption is not met by the SMILES string
CC(C1)CCCC1 which cannot be encoded as DeepSMILES (at least, while preserving the atom order).
The solution is simply to roundtrip such SMILES through such a cheminformatics toolkit to generate
the form required."

**Comment by TravelLeraLone** [comment]
Thank you very much! I must have missed that paragraph when reading the paper. Sorry for the bother.
